### ISSUE TITLE
Add Pentagine

### ISSUE THREAD

**Issue by davidgomes** [bebraw/jswiki#5]
https://github.com/davidgomes/pentagine

**Comment by bebraw** [comment]
Hi,

I added it amongst [lightweight engines](https://github.com/bebraw/jswiki/wiki/Game-Engines#lightweight). I also created a [JSter entry](http://jster.net/library/pentagine) for it.

Note that the wiki is open for edits so in case you need to tweak the entry, go ahead. :)
