### ISSUE TITLE
Game Engine Addition

### ISSUE THREAD

**Issue by mcscooter** [bebraw/jswiki#6]
Hello!

My company (PBS KIDS) has released a 2D tile based game engine built in HTML5. We'd love to have it added to your list of engines if possible.

https://github.com/PBS-KIDS/platypus

Example game: http://pbskids.org/wildkratts/games/monkey-mayhem/

Thanks!

Scott

**Comment by bebraw** [comment]
Hi,

The wiki is open for edits. So go ahead and add your library there. :)

**Comment by bebraw** [comment]
Closing as it looks like you got the library there. Thanks. :)
